---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCAJRD1Vm2Oxa06LPghsDuqBTVvBIEqcFWkiMwXUQ41qXhOuwSQgAGrvWbGuVlcEs13zQzHnJ7WsjXi7p3lcHk0WCHpS6mwdaqnGA8oszIzGeOKumNVq+T4O2ocwgO+uI8AQMCKgTvtNbcvtgkq7CoNKnIZR84xcuy4WCX/nVcN8o/5zAqnv6UCpcpBpEwRwCd0s7k1tt0t5uWneu6DtpED1BMyOCnwvWOFc3W4BJc6n+m2xdHvZrkEnXDZlx/sQ4ly2FxpJNAe9rAF1s5x5Rqv8RuKMLfPwxPcfrLeRSWKJipmDV1elSOAEovzvydbD5mtG5DlnO0iaLgDsDXG2vFln6Gv8utK+P8OYUC6GXO19hiawGnzek0/nj1ltH/wBuOnZIghMWKkKcvNaE8FWw0wU4E5LRnRIicJQ0niBMDK984oB8H34ius97e/tX3rKlrCee8Nz+ci6s1FvWuORRi888Twv/rljQyGHe2x79Mz8cVXO3JZ7HiVrzR8GEe1R8JAed8RQGflYZ6ViLI1wXkLzcOlgu6TZL6CwM8M86/puHwNuGkTPXrX9On21hUld5AfLY15h5FOWEYFsQ7+IhZVY9vn47824wAN1KmOj3+M241fm5S4+Dp45mhhE8IG0ByKROTWFIfxyPdsbFhz7ANowBBBUA6u1Z695sncNkYYjhWxwhFks8AcXZd2dSflkqKMaL6+IxxbmzSnL3zt+rcrPDlaiu/ede31+WDA+xmZXRlZFh8oiIiw
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
