apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: atlantis
    repoURL: https://runatlantis.github.io/helm-charts
    targetRevision: 5.4.0
    helm:
      releaseName: atlantis
      valuesObject:
        orgAllowlist: github.com/drewjprosser/*
        vcsSecretName: github-vcs
        ingress:
          host: atlantis.director.prossertech.com
  destination:
    server: "https://kubernetes.default.svc"
    namespace: atlantis
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true