apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis-resources
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/drewjprosser/argo-director.git
    targetRevision: HEAD 
    path: apps/atlantis
  destination:
    server: "https://kubernetes.default.svc"
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true