apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: awx-operator
    repoURL: https://ansible-community.github.io/awx-operator-helm/
    targetRevision: 2.19.1
    helm:
      releaseName: awx-operator
      valuesObject:
        AWX:
          enabled: true
          spec:
            ingress_type: ingress 
            ingress_hosts: 
              - hostname: awx.director.prossertech.com
            ingress_controller: nginx
            postgres_data_volume_init: true
            postgres_init_container_commands: |
              chown 26:0 /var/lib/pgsql/data
              chmod 700 /var/lib/pgsql/data
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true