apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: awx-operator
    repoURL: https://ansible.github.io/awx-operator/
    targetRevision: 2.19.1
    helm:
      releaseName: awx-operator
      valuesObject:
        AWX:
          enabled: true
          spec:
            ingress_type: ingress 
            ingress_hosts: 
              - hostname: awx.director.prossertech.com
            ingress_controller: nginx
            init_postgres_extra_commands: |
              sudo touch /var/lib/pgsql/data/foo
              sudo touch /var/lib/pgsql/data/bar
              chown 26:26 /var/lib/pgsql/data/foo
              chown root:root /var/lib/pgsql/data/bar
  destination:
    server: "https://kubernetes.default.svc"
    namespace: awx
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true