apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://operator.min.io
    targetRevision: 6.0.1
    chart: tenant
    helm:
      releaseName: tenant
      valuesObject:
        tenant:
          name: s3 
          pools:
          - servers: 1
            name: pool-0
            volumesPerServer: 4
            size: 10Gi
        ingress:
          api: 
            enabled: true
            host: s3.director.prossertech.com
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
          console:
            enabled: true
            host: minio.director.prossertech.com
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              
  - chart: operator
    repoURL: https://operator.min.io
    targetRevision: 6.0.1
    helm:
      releaseName: operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      # prune: true
      selfHeal: true