---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: atlantis-vcs
  namespace: atlantis
spec:
  encryptedData:
    token: AgB1F14rRITr7OkvWFJ+MaSWcg5y6h4EQMWSRzPSRDEunNPyCb01Kc6Kf82l2/y6RfvRDlwvEXXyFt51qrcglYMNo+5q4r73RPZ0hez3Dpuj2BVQzvaSMpviuwuoI6e54E2T9I8FflarPDzQEPwhWCPpYawpGE1evsp9KGL3bSzxDjYDcvRGra5XmH2gx8MvOVvcOGVQaYVFe20yw9bMyv31G7WHGwKE433LV/COmutttOcj1THzT2+YnnhGMCWFSofyB3PiO31eWql1gq95v+3lTE4VIO/hF7Xwp/E3WGE1eI5+7VB4ospUM1J1G6cXLEM9kYfqTOTZlkeQzannbZsN4XU3yOfP6xoTnOwrOJaexj/Mg/E3hhQ8QrmMg5TUjI988x+/WqdqiXY3c99il/IeqxzRKHVf9HVnGtxZfyD/hQlj32bcylEN87tFyPgv1fcO/gaIATxBJZzMpbX/bTYUnL6r9EyK1xXmSmZwvP6/6fE+xSA5DtnTZkNkksk+vdE/X2SlnF7oh8EfxQiw0sYcEn+rZndhoGxB52re5XZms+snPfjMIXmXHaj0Fy4s1f2/ia50Dr4QZM57x7k/t/khGSxBT7mgPMT6uclObararTBIwHIAHPe5ZQ8Cy3ooA8D1UPMhBck3Ju2kIC5z7Oc5zjqhTl42j4PNigyLJyBkGhXCHu+VYyRGBk9oqAV01XO+fRXyrPFuGgN9rpOqgvTyn51IZTpqvbXc2iwS3n/2m59HGXsissJb2g==
    webhook-secret: AgAnTSWBT6D/Yo5eGRAefyjSs3FMKQqD2VxSxe5JRvzc5Ral4nkGopH9HFVobwXbd+NxcDDzxAE4m2ji9pEvpe7NqOzqSh+VWzFQlTV431E5mpNf/rarEzomLLlTibXeE3Qm1ykrIiVR1bhxeAb5gbpzKIFvyebhRaVjWxZlrl/0toLL7IP43scNkzMB25qGhnSCnmvvZvkAQHM3k+72COFSXc+reIYde9Te3nL6bDavhm2kMpcQmtqK/PqcF7GXEBkeG7I7EInyfsDkqOaGCVRp3urvDqDYbezFuQWtEZ5oBc+leaOsWA7rb+9+oz/AORjCPUJVe0NZ1M/0f5zSFtLu7qWX1XH7sznQTgQY2GHw0UepTtTUCsQs7ZhPjLSj2gi60EI2nDip1Pa/Nm1i8JXe/viZulPHw2MAGwR3WOtAZ9xRs+3R4u0VOlDuWVfraqdLNQPgCGWT3jJ1E2Kz/i+TRfM/LUOLe28OYQmbDxnvMKJDcTRxVeJmYHEV3e1FewTMRHDHFdTRWNv1Fn1p2lFIrYApejGafKm5UVC2OOHoO2MB/VXGOmesnduiMW6485LhffEH9+4Hj2XlD/dHcjgwTV81NJr9Lat7rUOPPByMOA5VkzFsPEj9XtV7grPj6/6auOJQlaeGjxJvGgCw4sFaW4PosLzdb0XGrR23JfeK2ZUc6n1k1N81kPiY95OTXgjpBIbXK/5pK9pN5WcOQNq1KIF53CfvM1u5y/ay2KYZotCGwfdNrBNuTncJTiTffnegqkckTrYi0E8zp1lLVvLh2tg2bw7k0u+BFtX5Y6hpCwswC2Zycao3EtELSgUFpFMOFEgUHUZTek9L5RMCD8DQRQ1PqMzjJGsB6XiWI8NePQ==
  template:
    metadata:
      creationTimestamp: null
      name: atlantis-vcs
      namespace: atlantis
