---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: atlantis-vcs
  namespace: atlantis
spec:
  encryptedData:
    token: AgAe673jLUB2ZfSEkk0QJ28YgdG8Zav98a8+WvJuV+I65Us3S7nZyW5iZVUqnNbqTemcAqMHBGSTfjT0lByObTxyo8cJ4l5/HoACH1j52oRubd1FeDjSeMRz0IkurQxr0GE866LkVUTPgwbwZk5WG7qR0ZLqOOkIsN37xR6nup49H23U2TRUJpSwmpIDZWvrN16FXzX/FN3vXU2KxHzocOQkXU8R9SLIaTs5vEJn+TzLitVJNzlfPYhu9t846MAO8JLBsdaOY/nTlFCtpbVc7JJqusH2Fe5FbUQ/LQK/hoAY6n7qDNy35j2C/iPcF/CjpEynrYsyXS169xpxIzsPfj7nvSUE/O3Udsftc1sg291Rn2r8N6HrGuViH/Tt4+Y0qds+Zi4ki5Nedxq24h7CPscL3OIozfgLoKRMrTOuCLDoVympwnbqG1XlAfKY8N+1+enSLSSqWwmOW4GV/v5GVlDJPTTJJjZWXZY3vngYsdgW8pimBVAsGU3H1P7GZRsMn2EIcVIaWPOA1uFqzbtkSdEiHtgIhNPcTmvXri0nN+oKk6dxv1V69mvXgzhieDT9KtwtDAj5VAzF1H27DF0YgCN3LLZbkdBJ2rQer8PpBaTJJ7aV0qAh01fFG1Oyu8PoU6C4RthcVOzIiE4Ejtn3/BZpERbQQkUJHVw9GDlO3qc2iFoh2LM7fk3x+b25rFucBOmo/zaMC1HPH5fHIAtHFJY/MPfmup94MzY9l9q8g0HKC2LBQSRcXOmz
    webhook-secret: AgBofmAF+29p6WR/W4rENYLLvm8lBnOJQ3S79swktGKsG1d7AOARUBHBioAqSwoyVUe8yzBCi7D4rhI6UGEuzyqaKbwu3XzaZCLhFi1iECtkd+mNRwlUjJxd0bIvjHdUq0lku/kxE6FXVkk0C4kYtPJhhhCmqsWVidvekYeKPWpLue+eDo47APboP3T0dnOqf2sbt5BbWUdhQxpwwx3cGfejmQs+aD0aZei6IT0bwzVSHR8UXp60aEUjSaqLjsg57GnGapfdrfByU4V1VVKbyS5o/WpQ5n8DmwJlzZC9eeBO2M9yvgmqmYnP2GlWanYSYd7D3KIm5T+BZ6ATimijwmOVvBzo/PwtFs6DFRGzcl3bwjwJfVALqk84Zwh7eYnEr1IGBmmZOIEc3IJt2gdifI7T5q9sDsp7ApTykJNc1iaulf/6BXVa1d5MkQrFAFh+uo2Rg6CEr2gxrA+7OT5Ln0IEKtbSUoVN8Wt/A6wvNlM4EhbozsKbJ1TbpLNSFkG+JxNYoirxx1H7Ji3BTE1VhPcKkKP9QMN6UZkofZMBIa0Um43LDIhuLl1XE4X/TpNPG3tBEAAYSJwv9Z/9G0XejXbbI8kvODvk2o/evMlcQzJxYx9V3Hvt4JIhPMOMeCeANwH5DLaM0HF9OxFzjIxK9YDf3W6y2tY5jLreS52ThUj7LIYm9hXr3FkcuCbuqhBzghB6vyizOuJwamcBgkpSEYQcNDh3RP0/J9iO2bvXKX+xAscBgznchuaMRzhdm9+3zXnm0C7uypA/8QbHZ4Hidbc+x+O89T9zaGbPcZmdUrO4W+P/Aahez45cZUDFOUK6AUyIPgbU0CWoLTLIfE6AX+dO8gAtMUDk8MucoezptZll9g==
  template:
    metadata:
      creationTimestamp: null
      name: atlantis-vcs
      namespace: atlantis
