---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: atlantis-vcs
  namespace: atlantis
spec:
  encryptedData:
    token: AgCKb5zwhxZO9ydPGu/dgj6Ulv3OKeMuhW00k+PkjUH932CRoh1dCL8kHooG81qztwxw+Z5Rzp+zzm9P5TTIxIPhfW/8eExHPaAxRi8K4CSRUdF0l9VvS7SGoSgWInrCQq/b8mcLfF0QpdiUbb8nPjvw0vlZKGyOCZLnTx2zR5avVWV3SmzxC/+66YqxXnbd6R0kRi8bfwGJPVuA0Mr6/DlBuIeOg57w/sBqdT9fJjxCgiMAXjQrJMGkGjiFBMs7uO5kxTctT/xVFUoguDnYdivNmz8nGhqj8Xs3We7hHG9aHXFy73FoVb2JFl/0TVXx7EtiibuT0SFn6J3WP3rCm8DMWdxT/gXAaLtS0Za5SkxBBITapCk9U2XgfO9bSdOXcL3nZnIXTHZ61M3mSr1B05cmzpxQquKW/rpdJuiDlaM7o5F1ZBKuuQB/9ayC7dyL0/iZlSX2OpBfCpcZNW8e+TLJVf4Mxugp/x3hjgY5kwztjrdcROvKb/Rp0AQ+VwXNF5ozp6+ba4uAOhkcGYKmw+2AEd3J6HlZOnuHRkGgxSW15rQ/KCdLVhnpwXvcyWSI/uiW4FQVAKMekNZbTJPvjnwInLy3MIRkcuDiNa8hKQr6BjQomwE3Q811eQi4uctKgvDkiKLbpEki+b0glFYTlR5l2rFwyE4mdg3vJRNfPU8ayiEyCdX7xoJ1pntt0+o+7C3+9mcYyA4VcSJNwpFTGcXlQe815G/mnRU8yjhYfiUuAyDGrstkSrO6
    webhook-secret: AgBrsWheZjvEmk7gYynqiC9T94koWnILwNAgNXpLBXn/kdQan+LD/zjdt/7S/5QQOp8NoehABQo9eAuEep0Q5SlpiBR3xz7+k4+W6C0D199c2x8gnSbsdTfS531/cHuJim6CtEBKUFyLy/Aqh7Gs0lSu65mHxDxWZIZiKd38l2hF+XRIFlSf7q5+7og2BecPQ5HkgrO5YVOfOvQIieY8iqAuOkuh5e3b6HIp5Gop0ilBQnx1eTvAXuNRyDAuFpuXomEUOtJwW6lMfKHfrBs4f+0b1eOo0j95VHXLdMbfjTc1YcMTZ1H344IS/QRcBCanxV7RwDIugVu11KU0mDR2//H5wMSdgqmEgOA7h4atyPp1oGSczay865nZ/EHGQBbWoHzqvIWMh0VSVC+93/AfNauFhZ3mrVNnyb56wNvC2vCl/j93VZ1w1EdyeMxQ//ZwF8h0GsAC8i7AUJe71S2m6EGV8RRstzOZITUoR0BGc9bKyzXgAqYQM9KmmGiHUCyaD6dfbIQf5m8J52pTxUu+Vsglk5nwgnOmh3JD19vHHnfW76GWT+8JvmKHhFkf0knA6Oy3kcQIB9QoCT9guJyAvpq/xXWqwGreoPGFr8vA6bCO6YiQcybkueJcr3mguZC3FWiizdBRsS+At/4mJPyxnHgaaYCL1vgCTBkh4yYT9w7C9Cjl7QnFviHSkV94i6p+YFnEWf1gqURvqCoYrlkabYR/i33vVS3MqeA3bjueY4TGrXot2MVUYnVyTU1uXQIpQj1APcsFOr4R6ziCbHb+IsJwIOdH3kxXbXea0Sckf3VSQE8uBN1YK76sc/127kdq79faybEZs3fbreT/yaT/MmErBfz642xWQpBPcAo/Jx4tsA==
  template:
    metadata:
      creationTimestamp: null
      name: atlantis-vcs
      namespace: atlantis
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: atlantis-secrets
  namespace: atlantis
spec:
  encryptedData:
    address: AgB8FelTdGjpZ8fftp0l3xLinNDjuBrbTAssVS7cmbeNxCwwhnZEXSm1LDj33y6Wuy6PY/wGmym3ESA1+2tosDg9jo0d6fn7Db0pbZ6bH9gRN8H4pIRX0gJYIOr5b244k81eeDqQpCnhwxWkbQbhqILc6gk/iXGOyKUh5vfgtWYQ4CEwh9gGzFmcuMfrgnxP8GWgWgFolIb6VtXYCXo8Ge5rxkrSxFe8Wykrh21vTrPKG8usZuosFonRRVWsCHNC1CoIiCohLV6xmrNBXo6XuMUqL+gfLxyczptcXphl0q+aMJ05UO1H/4uZnSl6A4a0Ov+M6Ad9trQgNgpmMV584vIPSG+4M4exY3SJ1qqU3PV0M1tc9w5n2VwkH3vpI4BfGtxWo5NIxrlFQZCgJfU7qd4Qodviv1LVvAqOx3VsJ2oaj0BHEDqebg1xPGskcwq1q6z9udaL/NWUO5zDXE6vDtweSAqMb6BxU248+JvECcXNnliRZ79RJDXo2/Pz/ul111uPa6jBxS58neeAnIsFyVO8MaUQHNqjOOjT2YfsC6PafRetfBCqIZ+2LtQE4ToMXIPfUeFkcMKzSm2pMg0Cm9NL7cGxbVskVSje0tpZB62NFqtlXktSzfbHapS6KnCuoI1TAKsdwW6MDabYwECFpzFky7tGj9q0Z8Z8hxT//Gm56YG+Wq21RXk2JOOBhHas8DtCWEs+LJQ4MOItRdM6ytMKWIrnfEQUD9/YsyL+JwQHxwq+SubhiLsat4Q=
    password: AgAE4ifHjDTIShydPrDHCk273m+yLeJ0FNqpm42L/d4Qm/1c8BR0kiwoiJOGEkIx6rd88VCLyS33Dq/pv3Io0nPjZpDUaXNvYXxY5oCbHfFBBQtSJPGjDvdYP1ABzCvgLaTF2TY9hJic0ExzB5NzCgkb53icca16J04i8KGQSvj17cjCLWMgS/r5JR5ljl8F42Yug0PgvWD13wfJe0WnJGkSrVIjIU0hRZsHDvDJObxw3+j1sPwB/SX+MPNlbWEtuMCdEQ0ARLxO0cnDtpjvYepJGwhG1fUCd+Z3slncurGjbe/QXf/gyhuzQZ/HLONOMaMKJwZKMm72OuxkpSdphqzr7Cg4Wz8lirh1Yy5JlinXl+3DpXaU4E1pEQ+LZGew9nTOkOyZ24wS0e8W4KH3mxx/yv+ry7egw53XQs3UuxLWM92nqjzZ3QU7nhXDP0Xo1l77Rns/6dZPR7n7P549gdCJCU3LF/pLlwe2Y3O+8R28dXGkh0Ak/ln9cHEbvn+KoiVX2RgXSpzkOYMYhVF5mm/uH4jr1S5zu0i18TQmI3ETNAZh23wLpHBj64rAuK7yJ/vmvRvpFag1A/OZCk5ir2A3Fd03wZDTXAJnPQA8T0MauNzwbAifOkkPY88UyQaat6emOPtymD8Pb2N5DlGt5wo1fVHIJnNxIqTyvuygj+v76/8lV8JfxBhk2QKzhluqvEQvRg1buObmsA==
    username: AgB18JRP+Fk5w1HwYckQoUzdqvaJjjN5slL4zBGL5cAPv8qLJvo1E5U0Fmk7E8QiD3JA7ZHhiOQs42v3alI7yBSeTcJTHilVSxHuDVmuvDJ5tCRxP0eSSwSBAY8xH9nWdHJn1aS7SS1ENoHyiZ1I2dyfP7X2okE6SAjrW8A8WRx8LMkt9A9YYrLScUSWatrXifPfY2BqXg30DDn4pn9o7wsI5TWKAIOY2N61GATcncMqrlFikOwzpqWxUWHVEAiYFdExCNC4suGwfKLYEuHEu10/IqMt5cAP0tIvGlaoOKAumQleHVoI8kaHr4p61Cs4VaSdTdpWa30AU9NmKfBOxRD6lu9XwW5M1FuLWAbJpCFVzMZPefbpzNkhHm/s2uMHwkCR1s4vDGMz86jSIQsBhKYwAOtOBesevaek5u1LbPwgfQdA9Z9ntIqsKsPw5eM0xDiB5GciSP+b0EBFcmPJvuvsStswalyYgnzcdgCZg6ygX6Nys+kTXnSmLmGH/t2M4QF+RuwGUX9Wm+D2eGRMC5fTyUiCYFB7Oya8pmybx+4xeko03Mg8UilomkPTBQuHo9XeHr5Fm7NZzcOSKxNX//dFfYhIkmY3ohgx1cKq8XCWmd303QIjx06wqu2dyj7T4B76HegM4KNXCBt3Wx5l01Z6q8JorHCTjfHfFhhQQ7ThF7X4ybSpNEY7PIFI5WLBEno0v3ic4w==
  template:
    metadata:
      creationTimestamp: null
      name: atlantis-secrets
      namespace: atlantis
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: storage-user
  namespace: atlantis
spec:
  encryptedData:
    CONSOLE_ACCESS_KEY: AgBiDnwyLedXOK+u2MRoxtHCZlllYIiLMNn9c61DId5ownyofkgQvNzrWXZvrSCZgN+gUSU862BuPL9XbYjquTiLGRqbeF7smcg1SQWb2oxvVuiPVLGf4uq4vAUSG/hQBNOMCavOnu9B0tjo6f7O9ktpwGGxjzQjQ1VprtT73Pu2gS4SQn8sLXMXNNIKnbPCb1azZ9c1ZfwvxV0wc48D9MAvvpiqvQdoxav7mVtHlUl/n/3aCSs5g/olbDDCmCSQGkrGHVyktfIh9nbH/EED5ckNzeJE5yGXJLjRIJD4cdvnHHFnLAfVHXExiFase0PVxydpX3YEvsoSo8Ew0eX92IiU6t5aLAMjlAKf4gQoJtSbN2i1d4JF2EuJrb57qAf2WYV0VmHQs9a3a3eFs8wsnFyQ7AX8m+Nx3r1jqriJ4+QTSWTcS0OpDxee0O2mmwStqne4kAI8tkpcAPbHJR0hY512rQo2uRy6ri6p7gh7dn2lBVtFcHI1XbCjJkJlfFanW+NPmhG/JUQwuuCZS9FDR/QwvAwOxT1RHCZufiXUNTgcZX0rt8hzdBPHX9lv4yezCBtU4niY0akhf0rkAUCnzT05MbNK1CEXDPvA6dDUhLfsqkJFWMby05D7/CbT2u1IZ+X39JBJ65MzdmaGB498JNs60ZKyPx7lQ+OHy8dBFmU9sIFn7KRUzAEEgpHdNRYxLWCsLoK1Ek0o
    CONSOLE_SECRET_KEY: AgCyz+6Swzsh0kEzWO6z+IeRJItJVkT40XtEWIY5156VITOW8I53/XAgAIQ5pTplkUf9hmjZYByQujmVwimtiMcjZtomzlKBp8gXfHLSTi5n0M+xTO6GoM7Zgy+FrVAcE/7g7V95ZMY8hRj5YsKk/K7A0YYtfx0z+TF/HRfkGEyT5LpGjSW/v5cJSWgSZauboqpxymEXijf47iUZshCISFPD5YYBz437lDIo6jFijbktZMVssCOJDGhU3vr4clqDAhq+ix/6a8jHsSB93Z2FMDVX7g3qrFEdRjZo87q+ltdghvGreRx+vSo/7fnQLCrDWkV6k9PaSXvEFYV1bVq5VqSI4K3UEpkzHNwuzHg3K35pZ4NVX6m84CF7lqNpzI3fNTbQ4wcLUjE81EaLbdxFd38tt1lGETMXulLE5PiXltRB4UrDyrhu1FDB2uqUUFMFWj8+PJx/2qntEOf4IDf4gSRdkRc3pmxEQDn5cfBAFV6vNOdOdsgJdcJO8CZBHvkHgUjUK4Xke6GgD6PCKS88JmW3M4iR0dyLhm/8e+LHfcQEu4k8AhMEJsoTWQZyCzHjhyFPBzcouSZADe8UgsuQn9oGhl3hmgVQJr4XCnU0b1pCVyto+e+eUW87oADpgDEB2T3dmjufcHwvW2BinXyhPCkvmrxNlrlir4PYfqDNEpqsuIIT7G/fAyIFkKotMwugwLNJSEpDuGl68dYF
  template:
    metadata:
      creationTimestamp: null
      name: storage-user
      namespace: atlantis
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: atlantis-auth
  namespace: atlantis
spec:
  encryptedData:
    password: AgBik8EeXpUye/nVfidFlid5MYQ/DCkLYpnZ+8NFKRQz+dYOiUIMaEvKXh9Azl5lP5ksRnl4KBsZ6nxaO12B+FkZYquPEfY6eja18X/AHSnSMialu9YWtw7UbKA+qd+fzu/VcSVN/V5jWRBpFk7w7xspMlwWboiqFjOTuCx099pkyY2ptLRDbXRxyYuGaz8etSz/jpoWj/sH/Ctseu8RBDp+96pdhjoNwixD3xR4lxAdQT78cqYBxSYEH3YS8iK7IfIrxd39C3lgY5PIALp9cj+vM++GqH7e7f+Vca5VJsDq8qJo0Y8Lg+9HL7dpmem+I94+iyChRlf1R7/vdKtQ9J1Yrp3Ev5WUZJcmJJi8lY3BbyUIf2rVTmH4/cReKhRsX+fhtMW7kvmN4ZR+QS4uw2OrwDXzNFM2OUhL4LVngdv+y4ZM537eZcWYifTWScuY8CaN1TD+yqkrlIOqn0cQ0D/JfctuJ3+MP49nWIhgB6Mgy3Ls2AMaTGkH4Ypkfi41lBXNpI3QTb2evFYombuAtEODfiDMfzC4BwnCBuFjxH5rVorj+qD8IgSZVihh6jdO3q6Hgnr+m7MSL73IRmvjFVpJne5d55Tx9xLXh6RTc0ni8Lha3gMQnebrKtvRz+iUKJJT0QHwjp3fVHo+6kG9UwaguQQg4KpesgOOsYC/ApiVh8Rp5Bj6Nv6KH3ezZNMZQr72zuU2cZuBnw==
    username: AgAYzh3L5DTaRtupVFHxD45AXuNaFaZ0qXhTzMq/zkggedmV/x5MYFOTovwLLSVo/eE2ve0NcSHMVMzKxdUwK0XufOTfE/6eBWzdGfqpx0SUFJwRGaauYIrTb9ehOrTs0hRKyk7z5WxPS74HF6f7pzVr5At0kSjocITfcS8m/FneooeCffXLuJj2MzEqZFG4SeKxnPqR8y5ltn4/F33x9K2hSv1sTwSOSUEzEN58XMiyAeg5kS1Bwa5cHqJDluza8twwfWONKsQWfag75g8scRSkVqDt4tyFh5p966e/tCZW+RQCOmbNN4Bfx+ILBZgOb/OTV4/R5PgmMXp7H7rmcSJBHt36SChp8fC3AsoihZbgWgAtJqVLYklpnT/i2Hu0ON/qdVsC0ZiiCjvY1FuregEAtkYQqOmU1pasai5feQY3TmXzfUyID7KUe7v2dcwGTihT3njKfIsL18W5qMdUkJ9qM4WCQFZZmmG/7GQqldrG5XbaLsWp55f1kS8qwV2HjcfDqzmaKPDYfx67RNVPV831j7wTOevgQ0qDNG1j52TNdINC55Hxf0tnSIGvO1w5RnalEPtHyrhzDmVdKbYH69ApcRzpjkz8jArMD3Er3iK6Z8LrZsVV33dPqKIYm4+4L/PwE0QFHZNWaewYmaGw1GvY9whKM9UImEg/iyPUzQE/C/6uX3MXBk3N4ujSeZQTr3UjbH6Vp18WXA==
  template:
    metadata:
      creationTimestamp: null
      name: atlantis-auth
      namespace: atlantis
    type: Opaque
