apiVersion: minio.min.io/v2
kind: Tenant 
metadata:
  name: s3 
  namespace: minio
spec:
  pools:
  - servers: 1
    name: s3-pool
    volumesPerServer: 4
    size: 10Gi
    storageClassName: local-storage
    ingress:
      api: 
        enabled: true
        host: s3.director.prossertech.com
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      console:
        enabled: true
        host: minio.director.prossertech.com
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"