apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
  namespace: semaphore
spec:
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
      - name: semaphore
        image: semaphoreui/semaphore:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "1.0"
        ports:
        - containerPort: 3000
        env:
          - name: "SEMAPHORE_DB_DIALECT"
            value: "bolt"
          - name: "SEMAPHORE_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: sempahore-admin-creds
                key: password
          - name: "SEMAPHORE_ADMIN_NAME"
            valueFrom:
              secretKeyRef:
                name: sempahore-admin-creds
                key: username
          - name: "SEMAPHORE_ADMIN_EMAIL"
            value: "admin@localhost"
          - name: "SEMAPHORE_ADMIN"
            valueFrom:
              secretKeyRef:
                name: sempahore-admin-creds
                key: username
---
apiVersion: v1
kind: Service
metadata:
  name: semaphore-svc
  namespace: semaphore
spec:
  selector:
    app: semaphore
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: semaphore
  name: semaphore-ui
  # annotations:
  #   nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #   nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: director.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: /semaphore
        backend:
          service:
            name: semaphore-svc
            port: 
              name: http