---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sempahore-admin-creds
  namespace: semaphore
spec:
  encryptedData:
    password: AgAVkjNrObn95phB3F1cXIAo46zCvV3fMNNnrLPKpQGPruclGFtXXdEyn2jyE6UQfwzAEgCiqzjsip/C6OYlrH45jTpaIKrj5eIwxlr8F02C7IDh5UzmSTrk+YkMKHoLme/cf695wfD72xR/nDR/x2KNXqCqbLMDgwt0heyJFY0LoWZKnwlanewiwYZQSp+L+mMRv5MCCuGViIMxOKiyqAdZMOwIMhEc85xuUIRG5JtycR6MHCMkJbDGtihw0eWVxJ5wEOaVXzGwEyyZU76P25gLC4AKRdSaPJ/w1bmWP2kIu614QBRdI5m42jE8qpOnt/w7OKBspDVv8nWvgwtm3aLY7lx1AkOOvVVu96FjnydFv0sPm9gdkHHnzLUlMMBoDBvuC0Bfhmjoqpw0DudvISJfu0NurDnJqBpjnvPJESpoa4v/vMD2mSWmbUOXhzCRGM/DRK9Vk+XlGh4TL/lf1Duvhxj/a4/qQC2BvqH5TFVPpuJPIlFUqRwR4+rSj9FpbjC8f76YiJmBEjQphtRh1UgRKStZbJNobkaSyrpTUlzEyprfh6qTWeK2KZ/T50wW1Y2A9byCchw//qM6oY0x66xqOjg1oF7rYtZnoYuRKCfNlQ7gtuyYTIJLFmMk/HxKDfuQYYZgtuNer2KNOvS15QsIOdiL0u84Ek2DR15fslH0x84xslCnP4ls3wfOAKY2tYs861E4ePAKZg==
    username: AgCJk9n7dNOVNF19vwznZnSz1bouq9AePIk4GzcYwbY8H5tyc21f0ceEp2x4P0Kyk39UYeQxZNq3IKV1LX03IXPxXL6bRA+NmdOfxeze6dcqRuRnm5+2AvuhQ6CYC5KL9UIpiD2v+POU6tOWDJ6AiaFiJgwvjNjn/t1AXEKY/ZjlkhffdS9bH/hCNQ43wvKntLCatiqcN284bRh3aAzs+5gzDQOsrzpBDodJNn9iyVMmcLzriZRY7o9XyeH9D6UrDFKdBw2/nIyqeQ+nmAZcQuYgOnHAOfoQcJ9DICEuBF/66/ctxMP+blJFZpjvq1ME4LZe2KtgxnrDBHHWTgBYlcino1SrqEI0QvHkWf6VQfk7Z8aWKnMv0h+MhQFobg/rJLGK781LoM7X2eGJWVxt+gPqrkWtjIfBUEdgghKZdFy10xq+JTCAxnm3jf68dWQsX2JCMTOMiU0yV4tm+5Cl4pfPdsNWignoXsNnJWqUuiHjKosjGsGHdGwi2Kxb6J+RJpqRtjuzLFm9JxCYxYfB/dNcKnZD6B+y3Zui3DF5CoK1PZlMu5eNrbIeZ5mB1JOk2oc1+OneQsD+e71vl3RPCatUm6Ggid1wfozL4LQFWj/hNrIPUL0y3gwW6G+cL4qKBSp/goZGLy/6ORJDZbzYLdfVkdkGIfTOX3ZvsMOdUo8mckp7xf5MwVbj8+N+oAP+SeA9OXK9ow==
  template:
    metadata:
      creationTimestamp: null
      name: sempahore-admin-creds
      namespace: semaphore
