---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgCvv6r48rqcCJCKwPuI9XACD03Pzn9Pbb6lDMLCrY8tSanf4lFep/rsy8HRWOBiN/O6n5lB2bH6UJB5PuBo0JwkxCkFRLk4lUnfF2IcA5Mp38hnh00MYgsdXtetPpcyoong/4qEVU27LIxaKH9KQqF67unCB2GQjl/4ROMr9spZWZ8pM+Z9kYjcZvyqx166KE98f1NI9i3D/+FbhoiTJQu/asn/T0Vbu4TENzFe7hsWFgmqQ+MuaLBERvvYq7g8iw9q5TP1PRNprsFZwngKhOUVRqrm8NoUVzr1n3jMZO4Qud4GA2CYOOwOvC0nUj7XetTvPu3UREjSm3w/ujIQgSCr168Lq9kDNmcTxzPSyYBIFEv81MWhzeXVDLRqY8q0SC3AWeNmhEd/bHQnM3Wk3+ZicZOAs4fGTTYqIfM+PcIjU5ky72Pdhp6INsihPlHMlxuSiYicEiLvNEbfbiaRUB7vIgrrU7KATyYRhKs04m95UL1t6FlZ7HhRPmoy9/k1JMo2Y0Y1ys/XnAUVP4huEmFSc7h1gZZx2Fcbn4s5ebvHzdbZEZU/9nyJhup44mwq4Z12/uAQXeeLJoroOruhQbGMRHefelwNm+rFEFQZMToSIGpgmgeVjRu56bwDmcGYUXFdkIRYb+TW6MAJRZRAXyFz2mTJDHhKdYPV9zM57d8RXjYdadXcnZ33S3Kts0wYkB5GZHbba0vtZiXGngYZEzPscAdqfTu1hxH3O+0OV9+oOUReInOaqbi6vDXNL+VrI63KT1X9hI1M5I+5jaZQ0jQApIlcCZ98wu6ja7NoHY1iyXW7sMHm3frWzbsey0a1bx+lO4GN72EKq2TEpO36NUPh2s0RTNzmekE7W3OW2uWjfHLy4k0iaq2e/SVjWN3iwkf/UH44EDp0q9+e/x/JmGLqNA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
