---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgA6aSggQ1Z7Nm8FmVjwI4Q/0piS7SZaCjDRHWcZcRz2xeQWY9/lYvCyJfDf5d+o0xPSsw7XpfkTqN+vFautHAPIXhL8GUqG9JBA2WJvY7oI4gXI7tmYhFobvQddoQTdfUaK+UfJnRRjJyCxKGa0Ri7m+jzWFAsSGd7QR8vEFBJxnj38X9mEqkaAoSHymx7nUtc3TrkQatJRtT+0slEoQd/tXAgbhRLic3J4FLdBVmXl4FwXs97zJpBhUsKu2yuUslvZgMnrfASgQeRwWRAG02BsYG7D3Iv6jDiObdSmT5CxziUiYksPv07xIByP0wsr5cGQ9NZbZq5lgEVcc1nO9LRvgElX3UxknwG5RXXQrZHdF7/B83mWHoqxGMJ9rCxXTnqfPvEXTsYk1E6d/9N2ohPe8bR7pmIZByLV2D/5yD6LQbYxZic9ksto/0frcu1pUrc1E2gIyayej1ye5M1YWWaNDy0qYiL1k9Y9A80cG7AXt6bVQ1gVKeRa9USt/YQFdYDYKmh30FDwWFzCxrlh2BPnjAQ2HSZuaWZEcXRhfR7UGFs12kjYRTX9PZJsIoMSaAp0WiHtdg6N4zXabs5vXhNiTAbQmM501ANsW0HNxigqMVczXbgWRns1WdEQLF5BBRaZiBYIoBVWG/pEJ/94S6PeDuN4/zUro30g9FBHfqsDccu42fQWPc053u7K/hSO8OuJfobAyc+9tfiyWISxw3+KSLcJ4F3164AM1pRfA4LJSIGi1GPl6ixfaf0I5W4mDFKcd0ZCqQ1agrw+u1nwyNGoElVbt35j6HgKm8VP/dRHKaDWXpryG14F7LIMCcv7ywRZDYw2way8JTMMwmIy5TfCspcENQjJy5C+XwS6HjJsSnhtNrPu/BNTC3jLH6BXtNH8UVckLJJrTjy+bKCQTCPxMA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
