---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgBEcS8zr9HIwIM3fk2cdPk3KQrA/noi5CdRweUYUZRVig9R6Q4Ji87SPv7HXyxEiej8N3OvejlYvjU9HRLhBZqI9zs/r/VefeICTBlCDaZI4XGvoiFQzAFTLoBdbX4ltNVvDCrseHnqqOK7VyexSP5GxDGPiKGvn2o+UoUoW7MsxGYk/0G7oIty9lbTzikhktgtgjlPphc5TxOn2nujspDf7AlXBzraHkN3Wi7EbF+f11mkZMMt3NgIn0UW2F/MrMCACsyFf7hyehNJfAFKieanFzQISUO/dC7tQS+Kp+zH5fBBgDG14o05pUnRnNpMVoG/xKowb9gG2CAPf78NpobJD4AVkFKoIyLJAqr4usV029vnNRLUT+Hr5NbEla8EjfrpefUK9sGdzPY4AUWlxhtFkQoEnN5gwFBBOLNc+TzNKnK9jkTmK7W7dRwOODiBM+4Ui6pgoi6zCDXb/fIjlUBxIoYNAJRnpLJhmiwno9B4RKuDovf/KPLkJajTEQjyDI4OuSxcAbwkCnUPC3HnNmczbBY0qq5NzKVEyFqTpZEHkCf84Y9CyGWenlIJ9eXgOZCln+c1qCAkEVMXCwSBmjXGo36xC7zOWl/xWJJh5ntRBwkjHK8xaCqiuaOQNWXg9/2WW08F+FuK4/OPP0JClQmn8jPdutWroJJcwCBzzS4MiEbbX9yl22wXkZydPoTwZKxEo6/lc+eaxE/fMgpvK1E4ES4BcU7quZ7tyQGPaVlupL/bWH2Tf0tgiIt8nW8w7yvtK9iIqVj5Rz2po8V8QHUyCGmVTczrQMXbYJSPrlaQ3lWvsm6U2X8J46SJniZ2NI45IkqdiQSPyKlL5r5gyksq4xX7GAAtj07BoTAhFOXPpGgPo9s/QUqQFomt1deA3YcDnvHO2B6KeI//4Ky9mUj4mA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: cloudflared
