apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: argocd
  name: argocd-ui
spec:
  ingressClassName: traefik
  rules:
  - host: argocd-k3s.prossertech.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: argo-cd-argocd-server
            port: 
              number: 80