apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd-k3s.prossertech.com`)
      priority: 10
      services:
        - name: argo-cd-argocd-server
          namespace: argocd
          port: 443
    - kind: Rule
      match: Host(`argocd-k3s.prossertech.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argo-cd-argocd-server
          namespace: argocd
          port: 443
          scheme: h2c
  # tls:
  #   certResolver: default